# 工作流名称
name: Build Nchu Tools APP Docker Image

# push tags 时触发执行
on:
  push:
    tags:
      - 'v*'

# 定义环境变量, 后面会使用
env:
  IMAGE_NAME: nchu-tools-app
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  main:
    # 在 Ubuntu 上运行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Log into DockHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push image to DockHub
        run: |
          IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME

          # 转换成小写
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 从版本中删除 github-ref Or github-sha 前缀
          VERSION=$(echo "${{ github.sha }}" | sed -e 's,.*/\(.*\),\1,')

          # 从标签名称中删除 v 前缀
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${{ github.ref }}" == "main" ] && VERSION=latest

          # 保留前 7 位
          VERSION=${VERSION:0:7}

          # 打印 IMAGE_ID
          echo IMAGE_ID=$IMAGE_ID
          # 打印 VERSION
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME ${IMAGE_ID}:$VERSION
          docker push $IMAGE_ID:$VERSION

          docker tag $IMAGE_NAME ${IMAGE_ID}:latest
          docker push $IMAGE_ID:latest